### ISSUE TITLE
모든 element를 순회하는 대신 선택자를 이용하는게 낫지 않을까요?

### ISSUE THREAD

**Issue by skt-t1-byungi** [Seia-Soto/neatified#1]
https://github.com/Seia-Soto/neatified/blob/a1c63f12493afcd5834a5b3d308889a03fe5b7e4/scripts/neatified/neatified.js#L21-L38

모든 element를 순회하는 대신 선택자를 이용하는게 낫지 않을까요?
코드를 보다 저도 궁금해져서 검색해봤는데 확실한 정보를 찾지 못했습니다. 
그래서 간단하게 실험해봤는데요, 선택자를 이용하는게 더 빨랐습니다.  
(간단한 실험이라서 신뢰도가 낮지만...)

https://jsperf.com/single-queryselectorall-vs-queryselectorall-and-filter

**Comment by seia-soto** [comment]
이슈 남겨주셔서 감사합니다. 답변을 약간이나마 정리하느라 시간이 걸렸습니다.

먼저 저는 아직 어떤 엘리먼트에서 복사를 방해하는 요소(이벤트나 속성 등)가 등장하는지 특정하지 못했기 때문에 모든 엘리먼트에 대해서 함수를 처리하기로 했습니다. 그리고 `querySelectorAll` 메소드에서 `*`로 모든 엘리먼트를 선택했으며 해당 과정은 현재 @skt-t1-byungi 님이 말씀하신대로 유사하게 진행 중입니다. 단, 한 가지 차이점이라면 Array의 `from` 메소드를 사용하느냐 아니면 `...`(speared element)를 사용하느냐에서 차이점이 있겠습니다.

[남겨주신 레퍼런스](https://jsperf.com/single-queryselectorall-vs-queryselectorall-and-filter)를 참고하여 코드를 새로 작성해보면 아래와 같아집니다.

```js
elements = elements || [...document.querySelector('*')]
```

조금 더 직접적으로 쓰면 아래와 같이 됩니다.

```js
(elements || [...document.querySelector('*')]).forEach(...)
```

레퍼런스에서 테스트 벤치마크를 실행해보아도 가장 좋은 성능을 보여주고 있습니다. 앞으로 성능 향상을 위해서 작은 차이지만 비동기 작업이나 `forEach` 메소드 대신 `for` 문을 사용하는 방안도 검토하고 있습니다. 감사합니다.

![image](https://user-images.githubusercontent.com/30369714/64960575-7d62cb80-d8ce-11e9-8d53-829dbcaef5c4.png)


#### Ref

- [Array.from() vs spread syntax](https://stackoverflow.com/questions/40548213/array-from-vs-spread-syntax)

**Comment by skt-t1-byungi** [comment]
@Seia-Soto 애초 모든 엘리먼트에 이벤트를 거는의도였군요;; 제가 대충봤네욤.

**Comment by seia-soto** [comment]
앞의 글이 많이 복잡해져 하나의 답변을 추가로 작성합니다. 제가 질문의 주제를 약간 벗어난 것 같습니다. 죄송합니다.

말씀하신 선택자같은 경우는 위에서 언급한대로 특정 요소를 특정하지 못하기 때문입니다.

> 먼저 저는 아직 어떤 엘리먼트에서 복사를 방해하는 요소(이벤트나 속성 등)가 등장하는지 특정하지 못했기 때문에 모든 엘리먼트에 대해서 함수를 처리하기로 했습니다.

그러므로 모든 요소에서 이벤트 핸들링을 막고 속성을 제거하기로 했습니다.

혹시라도 특정 요소에서만 제거를 원하시면 아래와 같이 변경하신 뒤 사용하시면 됩니다.

- `p` 태그와 `br` 태그에만 함수를 실행하는 경우:

```js
// NOTE: scripts/neatified/neatified.js L22
elements = elements || Array.from(document.querySelectorAll('p, br'))
```

위 경우에는 첫 실행에만 `p` 태그와 `br` 태그만을 타겟으로 잡습니다. 이후 DOM 변경사항에서는 모든 요소에 적용되므로 `filter` 메소드를 사용해주셔야 합니다.
